Refactor
pjhartzell/nclimgrid-archive pull request #2
Opened 2022-01-25 15:46 UTC by pjhartzell

- COGs are now created separately from items with a dedicated class
- Daily and monthly collection and item creation live in separate functions
- Added tests

Before you submit a pull request, please fill in the following:

**Related Issue(s):**
None

**Description:**
See description above

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [ ] Documentation has been updated to reflect changes, if applicable.
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).

2022-01-25 17:03 UTC, gadomski requested changes
Added some inline comments, and one top level: When trying to run tests locally, I errored b/c `xarray` and `netCDF4` weren't installed -- these need to be added to `setup.cfg`.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/__init__.py
> +]
```suggestion
__all__ = [
    'create_cogs'
]
```

`__all__` is an enumeration of the classes and functions exported from the packaged. You only have `create_cogs` imported into the top level, so `__all__` should just include that.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/cog.py
> +                "base_href expected to contain 'daily' or 'monthly'")
```suggestion
                "nc_source expected to contain 'daily' or 'monthly'")
```

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/cog.py
> +            raise ValueError("status must be 'scaled' or 'prelim'")
https://docs.python.org/3/library/enum.html can be useful for cases like this, to explicitly enumerate the options.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/cog.py
> +            cog_list = self._cog_daily()
Same as above, an enum (https://docs.python.org/3/library/enum.html) can be more robust than string comparisons.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/cog.py
> +                temp_dir.cleanup()
This could be better handled by using the `TemporaryDirectory` context manager -- currently, if the code throws an exception during cogification, the data in the temporary directory might not be cleaned up properly.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/cog.py
> +                    temp_dir.cleanup()
Same as above, using the context manager would be more appropriate.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/cog.py
> +        result = subprocess.run(args, capture_output=True)
We're moving away from external `gdal_translate` calls; see https://github.com/stac-utils/stactools/blob/7a3a08f46ba07607f26dd36e60630d75dc9759d0/src/stactools/core/utils/convert.py#L16-L27 for an example (and an available function) for doing this with **rasterio**.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/cog.py
> +        return (temp_dir, nc_local_path)
One possible implementation would be to make this function a context manager.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/commands.py
> +        \b
Leftover `\b`?

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/commands.py
> +        collection.validate()
Might make more sense to validate before saving?

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/commands.py
> +        \b
Leftover `\b`?

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/commands.py
> +        collection.validate()
Same as above, might make sense to validate before saving?

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/stac.py
> +                nc_href = f"{base_nc_href.strip('/')}/{nc_url_end}"
So some of this logic (e.g. the year check) is duplicated from the cogification, indicating there could be some refactoring possible to reduce redundancy.

2022-01-25 17:03 UTC, gadomski commented on src/stactools/nclimgrid/stac.py
> +    return collection
This looks leftover from the template directory?

2022-01-25 17:03 UTC, gadomski commented on tests/test_stac.py
> +        collection.validate()
Some/all of these could use `stactools.testing.test_data`, specifically the `get_external_data` method: https://github.com/stac-utils/stactools/blob/7a3a08f46ba07607f26dd36e60630d75dc9759d0/src/stactools/testing/test_data.py#L42-L99. This would reduce local test time by caching the downloaded files in an `external-data` directory.

2022-01-25 17:03 UTC, gadomski commented on questions.md
> +1. Will we be indexing the current month of daily data, where the NetCDF file is marked as 'prelim'?. The prelim data is pre-populated with nodata values (-999) that are replaced with preliminary val
If it's not too much added complexity, I think **stactools** should support both, and we'll decide on the downstream side whether we'll use the `prelim` data at all.

2022-01-25 17:03 UTC, gadomski commented on questions.md
> +    - Example: `Band 1: time=80353 (days since 1800-01-01 00:00:00)`
What does the current format look like? Even if its a little ugly, it's not uncommon to use the NETCDF variable names as the COG names.

2022-01-25 17:03 UTC, gadomski commented on questions.md
> +3. Do we check for asset existence (local file or remote blob) during item asset creation?
Generally yes, or maybe add an optional `check_for_assets` argument to turn that on?

2022-01-25 17:03 UTC, gadomski commented on questions.md
> +4. Do we point at where the COGS will eventually live? Or is that updated later?
There's utilities for updating asset locations, so I'd say for now don't worry about it.

2022-01-25 17:03 UTC, gadomski commented on questions.md
> +2. The Cogger class only handles a local flat file destination
This is fine.

2022-01-25 17:03 UTC, gadomski commented on questions.md
> +3. If you COG a 'prelim' daily NetCDF, it creates blank COGS for days not yet populated with actual data
Would it be hard to check for blank cogs and not create those files in the first place?

2022-01-25 21:59 UTC, pjhartzell commented on src/stactools/nclimgrid/__init__.py
> +]
- Added xarray and netCDF4 to setup.cfg
- I went in the opposite direction and added all the stac functions and the Cogger class
```
from stactools.nclimgrid.stac import (create_cogs, create_daily_collection,
                                      create_monthly_collection,
                                      create_daily_item, create_monthly_item)
from stactools.nclimgrid.cog import Cogger

__all__ = [
    'create_cogs', 'create_daily_collection', 'create_monthly_collection',
    'create_daily_item', 'create_monthly_item', 'Cogger'
]
```
IIUC, this should allow these items to be imported as `from stactools.nclimgrid import create_cogs` and so on, while the `__all__` is for `from stactools.nclimgrid import *`

2022-01-25 22:34 UTC, pjhartzell commented on src/stactools/nclimgrid/cog.py
> +                "base_href expected to contain 'daily' or 'monthly'")
Changed all instances of `source_nc` and `base_href` to `base_nc_href` to be consistent with naming in `commands.py` and `stac.py`

2022-01-25 22:36 UTC, pjhartzell commented on src/stactools/nclimgrid/cog.py
> +            raise ValueError("status must be 'scaled' or 'prelim'")
As discussed, I decided to use a bool rather than an enum in this case, as it seems a more natural fit. It's either "prelim" or not.

2022-01-26 01:26 UTC, pjhartzell commented on src/stactools/nclimgrid/cog.py
> +            cog_list = self._cog_daily()
I added an enum for this. Not sure I'm using it in the appropriate manner, though.

2022-01-27 13:22 UTC, pjhartzell commented on src/stactools/nclimgrid/cog.py
> +        result = subprocess.run(args, capture_output=True)
I'm unable to limit the COG creation to a single "band" (date) from the NetCDF file using `rasterio's shutil.copy`

2022-01-27 13:33 UTC, gadomski commented on src/stactools/nclimgrid/cog.py
> +        result = subprocess.run(args, capture_output=True)
Ah right, forgot about that. In that case, don't sweat it it for now and keep doing as you're doing. -- it's something we should look into at the **stactools** level.

2022-02-01 15:44 UTC, pjhartzell commented on src/stactools/nclimgrid/cog.py
> +            raise ValueError("status must be 'scaled' or 'prelim'")
This is moot since `cog.py` no longer exists. But am using an enum for the 'scaled' vs 'prelim' status throughout new refactored code.

2022-02-01 15:45 UTC, pjhartzell commented on src/stactools/nclimgrid/cog.py
> +                temp_dir.cleanup()
Yeah, this awfulness has been eliminated.

2022-02-01 15:45 UTC, pjhartzell commented on src/stactools/nclimgrid/cog.py
> +                    temp_dir.cleanup()
Same reply as above.

2022-02-01 15:46 UTC, pjhartzell commented on src/stactools/nclimgrid/cog.py
> +        return (temp_dir, nc_local_path)
Moot. But thanks for the example you scratched together the other day.

2022-02-01 15:53 UTC, pjhartzell commented on src/stactools/nclimgrid/commands.py
> +        \b
click recognizes `\b` as a request to preserve formatting . Makes the help printout look nicer.

2022-02-01 15:54 UTC, pjhartzell commented on src/stactools/nclimgrid/commands.py
> +        collection.validate()
Yep. Changed.

2022-02-01 15:54 UTC, pjhartzell commented on src/stactools/nclimgrid/commands.py
> +        \b
Same reply as above.

2022-02-01 15:54 UTC, pjhartzell commented on src/stactools/nclimgrid/commands.py
> +        collection.validate()
Done.

2022-02-01 15:56 UTC, pjhartzell commented on src/stactools/nclimgrid/stac.py
> +                nc_href = f"{base_nc_href.strip('/')}/{nc_url_end}"
This is gone. New redundancies introduced, but likely not worth eliminating for now.

2022-02-01 15:56 UTC, pjhartzell commented on src/stactools/nclimgrid/stac.py
> +    return collection
Yep. Replaced with relevant data.

2022-02-01 15:57 UTC, pjhartzell commented on tests/test_stac.py
> +        collection.validate()
For now, using small test data uploaded as part of the repo. Not testing remote data on GitHub (have done so from my machine, though. Those tests are commented out)

2022-02-01 16:00 UTC, pjhartzell commented on questions.md
> +1. Will we be indexing the current month of daily data, where the NetCDF file is marked as 'prelim'?. The prelim data is pre-populated with nodata values (-999) that are replaced with preliminary val
For daily item creation (`create_daily_items`), you must specify whether the month is `prelim` or `scaled`. Although it will not see real use, the daily collection creation (`create_daily_collection`) uses some logic to determine whether the requested month of items is `prelim` or `scaled`.

2022-02-01 16:00 UTC, pjhartzell commented on questions.md
> +    - Example: `Band 1: time=80353 (days since 1800-01-01 00:00:00)`
Will leave as is for now (default from GDAL's cogger).

2022-02-01 16:04 UTC, pjhartzell commented on questions.md
> +3. Do we check for asset existence (local file or remote blob) during item asset creation?
Existence checks inserted for local data and when not downloading remote data (remote download will fail if remote data does not exist). Might be nice to check remote file for existence before downloading and gracefully fail.

2022-02-01 16:04 UTC, pjhartzell commented on questions.md
> +4. Do we point at where the COGS will eventually live? Or is that updated later?
OK

2022-02-01 16:04 UTC, pjhartzell commented on questions.md
> +2. The Cogger class only handles a local flat file destination
OK

2022-02-01 16:04 UTC, pjhartzell commented on questions.md
> +3. If you COG a 'prelim' daily NetCDF, it creates blank COGS for days not yet populated with actual data
It now looks inside the `prelim` files and only creates data for days with valid (not `nodata` values) data.

2022-02-01 19:30 UTC, gadomski approved these changes
✨

2022-02-01 19:47 UTC, merged